Repository boson-project/buildpacks, pull requests merged in 2020-11, with the labels that each got.

#43 fix(deps): sync node.js builder with faas CLI
  buildpacks/nodejs/runtime/package.json
Labels: runtime/nodejs

#50 fix: add --nodocs to dnf install to reduce image size
  stacks/nodejs/build/Dockerfile
  stacks/nodejs/run/Dockerfile
Labels: artifacts/stacks, runtime/nodejs

#53 fix: don't assume /workspace in go builder
  buildpacks/go/bin/build
Labels: artifacts/builders, runtime/go

#55 chore: bump release-please-action to v2.9.3
  .github/workflows/ci.yaml
Labels: ci

#52 ci: ensure that the build is run on pull requests
  .github/workflows/ci.yaml
Labels: ci
